#!/usr/bin/env bash
#print best school 10 times and use if,elif and else
i=1
while [$i -le 10]; do
if [$i -eq 4 ]; then
echo "best school"
echo "bad luck"
elif [$i -eq 8 ]; then
echo "best school"
echo "good luck"
else
echo "best school"
fi
((i++))
done
