#!/usr/bin/env bash
# Bash script that displays lines containing the 'bash' word,plus allows you to easily get the PID of your bash process
# shellcheck disable=SC2009
#	-You cannot use pgrep

ps -faux | grep "bash"
